### ISSUE TITLE
Override question. Not necessarily a bug

### ISSUE THREAD

**Issue by 109JB** [gnea/grbl#473] opened 2018-06-09 18:07 UTC
I finally have a chance to do some work updating my GUI and had a question. It may or may not be a bug.

So lets say you have a programmed feed rate of 100 mm/min and set the feed override at 80%. In this case, Grbl reports the feed rate as 80 mm/min.

Now lets say you have the spindle speed programmed at 1000 rpm and the spindle override at 80%.  Grbl still reports the spindle speed as 1000 rpm. I would have expected it to report 800 rpm.  Is this a bug or is it intentional?

**Comment by chamnit** [comment] 2018-06-09 19:18
Probably a bug. I may have forgotten to do that conversion in the report.

**Comment by chamnit** [comment] 2018-06-09 23:01
I can verify that this is a bug. It doesn't update the spindle override when idle. Once motion is active, it will update.

**Comment by chamnit** [comment] 2018-06-09 23:38
This is a duplicate of #268. Closing.

**Closed by chamnit** 2018-06-09 23:38 UTC
Labels: bug
