### ISSUE TITLE
support servo as spindle (marge request in fact)

### ISSUE THREAD

**Issue by Cdriko** [gnea/grbl#61] opened 2016-12-12 14:08 UTC
Hello
I want to use a servo in place of a spindle (for a vinyl cutter/plotter).
I find this good work made by 
[robottini](https://github.com/robottini/grbl-servo)
is it possible to merge it to the master branch?

thanks

**Comment by chamnit** [comment] 2016-12-12 15:46
@Cdriko : Perhaps in v1.2. Not this recent release. I'll put this link in my todo notes and close this issue.

**Closed by chamnit** 2016-12-12 15:46 UTC

**Comment by langwadt** [comment] 2016-12-13 21:26
It would also be useful for using an RC brushless motor and speedcontroller for a spindle

**Comment by Cdriko** [comment] 2016-12-13 22:02
good idea .
but for the moment I find a solution with a L298 and a solenoid
thanks

**Comment by sbma44** [comment] 2017-02-08 03:28
I've just built a 4xidraw and would love to get onto a modern version of grbl for the fixed corexy homing behavior, but servo support is a blocker. Would you accept a PR for this functionality?

**Comment by Danccls** [comment] 2020-02-01 23:15
I'm testing a servo on the spindle. Later I want to use a brushless RC motor ans a ESC as spindle.

The problem is that maximun speed must be configurated to 255, and the spindle selector moves betwen 0,100 or 200. Actually I only have two speeds.

I can use the command M3 Sxxx (where xxx is the speed of the spindle from 0 to 255), but it will be usefull the ability to select the steeps of spindle selector, as 5 or 10, not the present 100.

Regards.
