### ISSUE TITLE
Spindle speed reporting wrong

### ISSUE THREAD

**Issue by 109JB** [gnea/grbl#30] opened 2016-11-01 21:31 UTC
I noticed that when $13=1 to report inches, and then calling a $G, the S-value is wrong by a factor of 25.4. For example, if you Issue S500, the $G report shows S=19.7 if $13 is set to 1.

**Comment by chamnit** [comment] 2016-11-01 21:45
@109JB : I can't reproduce this issue. What version are you using?

**Comment by 109JB** [comment] 2016-11-02 03:24
I'm not sure why but I can't reproduce now either..  My Arduino has been reset since then, but the firmware hasn't been updated since I saw this happen.  I am using Grbl 1.1c  [VER:1.1c.20161012:]

I know that it happened, because I thought it odd, and changing $13 would switch the reported S value between 500 and 19.7 and I realized it was a 25.4 factor. not sure what to say.

**Comment by chamnit** [comment] 2016-11-04 15:25
@109JB : I'm closing this issue until we can reproduce this error, but so far, it seems to be operating as intended.

**Closed by chamnit** 2016-11-04 15:25 UTC
